version: '3.3'

services:
  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379

  redis-cluster:
    image: grokzen/redis-cluster:6.2.1
    ports:
      - 7000-7005:7000-7005
    environment:
      REDIS_CLUSTER_IP: '0.0.0.0'
      IP: '0.0.0.0'
